Initial release for Salicru driver
networkupstools/nut pull request #1199
Opened 2021-11-22 23:00 UTC by xbgmsharp

Initial release for Salicru driver to help with #732

2021-11-23 10:26 UTC, jimklimov approved these changes
Looks great, thanks! I assume it has tested well with the model you have?

Don't be shy, add yourself to (C) stack in the new files ;)

2021-11-23 11:51 UTC, jimklimov commented
Since my comments above can be addressed "immediately" or later, I'll shelf this PR for a day or two and merge (if there is no feedback before that, to change the plan)

2021-11-23 11:57 UTC, xbgmsharp commented
Thanks. Will update the code accordingly. Trying to install the official software to compare the data.

2021-11-24 08:58 UTC, xbgmsharp commented
Update mapping and confirm output data.

2021-11-24 15:45 UTC, jimklimov requested changes

2021-11-24 22:09 UTC, xbgmsharp commented on drivers/salicru-hid.c
> +  { "unmapped.ups.powersummary.iproduct", 0, 0, "UPS.PowerSummary.CapacityMode", NULL, "%.0f", 0, NULL },
will update to use `experimental.*` data points

2021-11-24 22:11 UTC, xbgmsharp commented on drivers/salicru-hid.c
> -  { "test.battery.start.quick", 0, 0, "UPS.Output.Test", NULL, "1", HU_TYPE_CMD, NULL },
Probably does, but did not test.

2021-11-25 08:13 UTC, jimklimov commented on drivers/salicru-hid.c
> -  { "test.battery.start.quick", 0, 0, "UPS.Output.Test", NULL, "1", HU_TYPE_CMD, NULL },
Then maybe better leave those lines in place, possibly commented away, so whenever someone can/wants to test them, it would be easier.

2021-11-25 09:26 UTC, xbgmsharp commented
Rename unmapped.* to experimental.* data points
Add untested instant commands, commented out

2021-11-25 14:51 UTC, jimklimov approved these changes
Thanks, looks good now :)

2021-11-25 14:51 UTC, merged