nut-scanner does not detect UPS with unknown ProductID
networkupstools/nut pull request #1384
Opened 2022-04-20 23:00 UTC by vincentto13

nut-scanner is not able to detect properly UPS if product id
is defined as 0xffff in usb_device_table. For instance entry:

{ 0x2e51, 0xffff, "usbhid-ups" }

Does not recognize properly my UPS, which appears as

Bus 003 Device 002: ID 2e51:0000 EVER ECO PRO AVR CDS

with lsusb command, but is fully supported.
I don't know if setting 0xffff in usb_device table was intentional,
for this purpose, but this commit treats ProductID from
usb_device_table, as bitmask while traversing over usb devices.

The following approach resulted in, the following output running
nut-scanner with my Ever UPS attached:

./nut-scanner -U
Scanning USB bus.
[nutdev1]
    driver = "usbhid-ups"
    port = "auto"
    vendorid = "2E51"
    productid = "0000"
    product = "ECO PRO AVR CDS"
    serial = "XXXXXXXXXXXXXXXXXXXXXXX"
    vendor = "EVER"
    bus = "003"

2022-04-21 12:26 UTC, jimklimov commented
Hi, a ProductID (and VendorID for that matter) is not a mask but a number of entity assigned by some authority (products listed by their vendor, vendors registered with USB IF). Except that many boxes and their makers do a poor job at this or blatantly lie, using bogus numbers.

Proper diligently used Product IDs let us differentiate an MS keyboard from an MS mouse from an MS headphone or a hypothetical MS UPS - and separate the UPSes of same vendor using different protocols over USB. And they let us match a driver (and dialect subdriver) suitable for this or that device.

So here a better solution is to add the (parsed) comment+macro for new vendors, and USB_DEVICE entry for the new vid:pid pair to the driver which works best (also bump driver.list.in for HCL and the DDL if possible). And hope this really is the only protocol using such pair...

2022-04-21 12:27 UTC, jimklimov requested changes
Mask is not the way.

2022-04-21 13:54 UTC, vincentto13 commented
Cool I pretty agree with proposed solution. I wanted to make it smart, and bitmask seemed to be a generic solution, but you're right that, that if Vendor 0x2e51 would release keyboard with different ProductID, this commit would find keyboard as UPS ;). I was thinking about inheriting from driver common, as the partial_support. But this would be like major refactor, which I'd like to avoid, as I don't know the NUT code.


I'll go with your proposed solution, but can you please explain what is HCL, and DDL in this context ? Btw thank you for commits that made Ever UPS supported by NUT :)

2022-04-22 09:51 UTC, jimklimov commented
Regarding HCL, you found it :) Currently it is more of a source for documentation (and generated web site) that allows to semi-structurally collect user reports (and some comments) of what drivers worked for which devices. It is also a reference for developers e.g. to identify unrelated products (brand, protocol) having same basic identification (often not re-branded USB chip info).

The DDL is tracked in a nearby repo https://github.com/networkupstools/nut-ddl and represented at the website; section https://networkupstools.org/ddl/#_file_naming_convention details how to contribute to it. This is a detailed report of which devices were known to work with which drivers in which NUT releases, what data points they reported, what commands they supported, etc.

The line you posted seems to be in `tools/nut-scanner/nutscan-usb.h` which is a generated file, based on collection from roughly `drivers/*-hid.c` during build, so the SCM-trackable solution is to update in this case the original `drivers/ever-hid.c` file. Since this is about a new product ID for existing vendor, see if adding a line to `ever_usb_device_table[]` there and rebuilding NUT would let your deployment discover your UPS model "out of the box".

As for refactoring existing committed code, sure there are a lot of "improvement opportunities" so feel welcome to dig more into NUT codebase to make it better :) Keep in mind that nut-scanner in particular may be complicated, since on one hand it uses `libltdl` to optionally use third-party shared objects - e.g. its binary is not pre-compiled to require libusb, libsnmp and so on, but picks them up at run-time if available or skips if not. On another hand, most of its logic is delivered as a separately usable `libnutscan` for which the `nut-scanner` front-end program is just one of possible consumers. So sharing more code between it and the bulk of NUT may require some trickery with source code layout and/or "helper libs" in the makefiles to compile same sources into different object files; there already is precedent for multiple-use of serial-port code, etc.

2022-04-22 15:59 UTC, vincentto13 commented
Thanks for detailed explanation. I've created another Pull Request #1387, and once the change will be merged, I'll create a second one against https://github.com/networkupstools/nut-ddl. This one can be discarded I guess.

2022-04-23 18:43 UTC, closed without merging

2024-06-27 09:05 UTC, jimklimov commented
As a heads-up, recent NUT releases have added a `subdriver` option for `usbhid-ups` driver, so you can force it to try a mapping of your choice against given (explicitly) `vendorid`, `productid` and perhaps other fields that let us identify the device uniquely, see #1369 and #2058