Add new driver for UPS supporting microlink protocol
networkupstools/nut pull request #2663
Opened 2024-10-17 12:59 UTC by tom1422

An experimental driver for APC microlink protocol devices that I would like to contribute to the project. 

Will need more work to ensure it follows NUT convention more closely (e.g. Variables being defined not at start of functions). 

## General points

- [ ] Described the changes in the PR submission or a separate issue, e.g.
  known published or discovered protocols, applicable hardware (expected
  compatible and actually tested/developed against), limitations, etc.

- [ ] There may be multiple commits in the PR, aligned and commented with
  a functional change. Notably, coding style changes better belong in a
  separate PR, but certainly in a dedicated commit to simplify reviews
  of "real" changes in the other commits. Similarly for typo fixes in
  comments or text documents.

- [X] Please star NUT on GitHub, this helps with sponsorships! ;)

## Frequent "underwater rocks" for driver addition/update PRs

- [ ] Revised existing driver families and added a sub-driver if applicable
  (`nutdrv_qx`, `usbhid-ups`...) or added a brand new driver in the other
  case.

- [ ] Did not extend obsoleted drivers with new hardware support features
  (notably `blazer` and other single-device family drivers for Qx protocols,
  except the new `nutdrv_qx` which should cover them all).

- [ ] For updated existing device drivers, bumped the `DRIVER_VERSION` macro
  or its equivalent.

- [ ] For USB devices (HID or not), revised that the driver uses unique
  VID/PID combinations, or raised discussions when this is not the case
  (several vendors do use same interface chips for unrelated protocols).

- [ ] For new USB devices, built and committed the changes for the
  `scripts/upower/95-upower-hid.hwdb` file

- [ ] Proposed NUT data mapping is aligned with existing `docs/nut-names.txt`
  file. If the device exposes useful data points not listed in the file, the
  `experimental.*` namespace can be used as documented there, and discussion
  should be raised on the NUT Developers mailing list to standardize the new
  concept.

- [ ] Updated `data/driver.list.in` if applicable (new tested device info)

## Frequent "underwater rocks" for general C code PRs

- [ ] Did not "blindly assume" default integer type sizes and value ranges,
  structure layout and alignment in memory, endianness (layout of bytes and
  bits in memory for multi-byte numeric types), or use of generic `int` where
  language or libraries dictate the use of `size_t` (or `ssize_t` sometimes).

- [ ] Progress and errors are handled with `upsdebugx()`, `upslogx()`,
  `fatalx()` and related methods, not with direct `printf()` or `exit()`.
  Similarly, NUT helpers are used for error-checked memory allocation and
  string operations (except where customized error handling is needed,
  such as unlocking device ports, etc.)

- [ ] Coding style (including whitespace for indentations) follows precedent
  in the code of the file, and examples/guide in `docs/developers.txt` file.

- [ ] For newly added files, the `Makefile.am` recipes were updated and the
  `make distcheck` target passes.

## General documentation updates

- [ ] Updated `docs/acknowledgements.txt` (for vendor-backed device support)

- [X] Added or updated manual page information in `docs/man/*.txt` files
  and corresponding recipe lists in `docs/man/Makefile.am` for new pages

- [ ] Passed `make spellcheck`, updated spell-checking dictionary in the
  `docs/nut.dict` file if needed (did not remove any words -- the `make`
  rule printout in case of changes suggests how to maintain it).

## Additional work may be needed after posting this PR

- [ ] Propose a PR for NUT DDL with detailed device data dumps from tests
  against real hardware (the more models, the better).

- [ ] Address NUT CI farm build failures for the PR: testing on numerous
  platforms and toolkits can expose issues not seen on just one system.

- [ ] Revise suggestions from LGTM.COM analysis about "new issues" with
  the changed codebase.

2024-10-17 14:13 UTC, desertwitch commented
Wow, thanks for the effort, I'm sure many people will love to see this protocol supported. 💯  Out of general interest, what was the UPS device that you built this around and which variables were you able to extract that worked for your device? Can you post a data dump of the UPS variables of your device when running your driver?

2024-10-17 15:02 UTC, tom1422 commented
> Wow, thanks for the effort, I'm sure many people will love to see this protocol supported. 💯 Out of general interest, what was the UPS device that you built this around and which variables were you able to extract that worked for your device? Can you post a data dump of the UPS variables (of your device) when running your driver?

Thank you, here's some of the info as requested:

The device i used was an SMT750i (that is too old to support modbus). 

I also tried it on a friend's UPS (some larger and or newer units that do support modbus) and they seem to all expose more or less the same variables (there's probably still more configurations that need supporting). 

Here is the dump from upsc for my device: (removed serial number)
```
Init SSL without certificate database
battery.charge: 100.000000
battery.date: 2019-02-01
battery.date.maintenance: 2023-07-31
battery.runtime: 16250.000000
battery.voltage: 27.125000
device.id: APCUPS
device.mfr.date: 2010-02-05
device.model: Smart-UPS750
device.serial: xxxxxxxxxxxx
device.type: ups
driver.debug: 2
driver.flag.allow_killpower: 0
driver.name: apc_ul
driver.parameter.pollinterval: 1
driver.parameter.port: /dev/ttyUSB0
driver.parameter.synchronous: auto
driver.state: updateinfo
driver.version: 2.8.2.1095.1-1096-g07169142d
driver.version.internal: 0.01
experimental.output.energy: 1434365.000000
input.frequency: 50.078125
input.quality: Good
input.sensitivity: High
input.transfer.high: 264.000000
input.transfer.low: 216.000000
input.transfer.reason: AcceptableInput
input.voltage: 233.187500
outlet.group.0.delay.reboot: 8.000000
outlet.group.0.delay.shutdown: 180.000000
outlet.group.0.delay.start: 0.000000
outlet.group.0.name: UPS Outlets
outlet.group.0.status: StateOn
outlet.group.0.timer.reboot: Inactive
outlet.group.0.timer.shutdown: Inactive
outlet.group.0.timer.start: Inactive
outlet.group.count: 1
output.current: 0.000000
output.frequency: 50.078125
output.voltage: 233.187500
output.voltage.nominal: VAC240
ups.delay.reboot: 8.000000
ups.delay.shutdown: 180.000000
ups.delay.start: 0.000000
ups.efficiency: unavailable
ups.firmware: UPS 09.4
ups.load: 0.000000
ups.power: 0.000000
ups.power.nominal: 750.000000
ups.realpower: 0.000000
ups.realpower.nominal: 500.000000
ups.status: OL
ups.temperature: 27.000000
ups.test.interval: Startup_14_After_last
ups.test.result:
ups.timer.reboot: Inactive
ups.timer.shutdown: Inactive
ups.timer.start: Inactive
```

(I have also updated the pull request with some extra details)

2024-10-17 18:53 UTC, jimklimov commented
Sounds great, and CI (or local `./ci_build.sh`) should help weed out most warnings quickly :)

Did you find a protocol definition, or was this "lock-picked" somehow?

2024-10-17 19:13 UTC, jimklimov commented
As for USB support, if you mean something greater than `/dev/ttyUSB0` which is serial as far as code is concerned, perhaps `nutdrv_qx` can be a sort of model for a driver that supports both types of media; all others are for some one media.

2024-10-20 21:34 UTC, jimklimov requested changes
Taking a look at this PR about why it failed CI (and to read a bit more into code, although still cursorily), got some early comments and simple fixes here.

I suppose the next big issue to pass NUT CI requirements across the board would be a bit of dumbing down the C language syntax (e.g. requiring the declarations to be in first lines of scope, not further in code), so it builds on old systems too.

2024-10-20 21:34 UTC, jimklimov commented on drivers/apc_ul_util.h
> +	{__VA_ARGS__}
Looking forward to seeing whether the different compiler generations (and their C99+ settings) in the NUT CI farm would accept this syntax or find it too revolutionary :)

2024-10-20 21:34 UTC, jimklimov commented on drivers/apc_ul_util.h
> +	int array_length;
Why not e.g. `ssize_t` if we want signed (and to fit into compiler-guaranteed array sizing)?

2024-10-20 21:34 UTC, jimklimov commented on drivers/apc_ul_util.h
> +	int command_length;
Can this "length" be negative? Would a `(s)size_t` be better here?

2024-10-20 21:34 UTC, jimklimov commented on drivers/apc_ul_util.h
> +	int length;
Can this "length" be negative? Would a `(s)size_t` be better here?

2024-10-20 21:34 UTC, jimklimov commented on drivers/apc_ul_util.h
> +								   uint8_t *master_password_verify);
Can "length"'s in these methods arguments be negative? Would a `(s)size_t` be better here?

Also. for methods that populate a caller-provided string (e/g/ `fqun_to_string`) I'd prefer seeing an argument to track the allowed buffer length (decremented and consulted in the logic).

2024-10-20 21:37 UTC, jimklimov commented
@tom1422 : hm, I got too used to having maintainer write access to forks' branches that PRs come from.
Can't push my fixes for some compiler complaints here :-}

2024-10-20 21:43 UTC, jimklimov commented on drivers/apc_ul_util.c
> +				snprintf(dest + ptr_string, 12, "[%-3i, %-3i]", current_fqid.array_index % 256, current_fqid.array_length % 256);
`13` not `12` here, to allow for `\0` always.

Also note the other comment, about adding an argument to check for not overflowing a caller-provided buffer size.

2024-10-20 21:45 UTC, jimklimov commented on drivers/apc_ul_util.c
> +		for (uint8_t i = 1; i < exited.array_length; i++)
`int i` (beside moving declarations to start of scope)?

2024-10-20 22:29 UTC, jimklimov commented
Per offline discussion, completion of this contribution will likely be delayed, so marking Draft for now.

2024-10-24 13:19 UTC, desertwitch commented
I just saw the driver file is empty with the latest force push, what's going on? Refactoring?

2024-10-24 13:28 UTC, tom1422 commented
> I just saw the driver file is empty with the latest force push, what's going on? Refactoring?

I'm talking to jimklimov about this, but I have decided to remove it while I sort out / determine what's best (legally speaking). I hope you can understand and please feel free to close the pull request (if you think that would be better, I dont mind opening one in future or contributing on this one directly).

2024-10-24 13:29 UTC, desertwitch commented
> > I just saw the driver file is empty with the latest force push, what's going on? Refactoring?
> 
> I'm talking to jimklimov about this, but I have decided to remove it while I sort out / determine what's best (legally speaking). I hope you can understand and please feel free to close the pull request (if you think that would be better, I dont mind opening one in future or contributing on this one directly).

Ah I see, I figured something was going on behind the scenes... 😉 
All good, was just curious and still appreciate all the effort you've put into this.

2024-12-01 13:22 UTC, jimklimov commented
Although currently suspended, cross-linking to issue #1426

2025-05-21 06:03 UTC, desertwitch commented
Not to poke the hornet's nest, but... any news on this?

I'm guessing the issue at hand has something to do with it being proprietary?
How does this compare against older APC protocols?

Maybe a blue-eyed type of question but is it very utopic to get APC to sign off on this?
NUT being a long-standing and well-established project and all...

I'm sure it'd be a welcome addition for many users, so... is it likely to ever happen? 😉

2025-10-04 10:22 UTC, closed without merging

2026-07-11 18:15 UTC, jimklimov commented
Another cross-link: PR #3406 was independently contributed later to add a MicroLink driver. I can't say how much the two attempts at this overlap in features, e.g. if there are any tricks that code by @tom1422 did that the other (merged) driver can not do yet.