Add Russian translation for NUT-Monitor
networkupstools/nut pull request #806
Opened 2020-07-17 08:43 UTC by melenki

Add Russian translation for NUT-Monitor

2020-10-07 12:55 UTC, jimklimov requested changes
Thank you for this contribution. There's a few typos commented in the review, and a lot more cases where a generic "device" is translated as an "UPS" at expense of other device types that NUT can handle.

I understand there may be a point in providing a tool to end-user workstations to monitor specifically their UPSes and not care about other device types; I think it may be reasonable then to either deliver a separate similar locale file for those and maybe pick one or another by some packaging post-install magic, or to maintain this as a templated `.po.in` file with substitution of strings for generic or specific translation of device during build (as chosen by some new `configure` script option).

Then also there's the matter of hiding "NUT" from the app title and dropping the copyright, license and project/authorship strings which I think is a blocker.

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "Вы уверены, что хотите удальть это из Избранного ?"
Опечатка: "удалИть"

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "Добро пожаловать в мониторинг ИБП"
Здесь и далее - NUT мониторит не только "ИБП" (UPS), но и управляемые розетки (ePDU), солнечные батареи, дизель-генераторы, блейд-серверы с IPMI (с точки зрения питания - умная розетка на полдюжины серверов) и т.п.

Хорошо бы придумать универсальный термин (и аббревиатуру) для "устройств, связанных с электропитанием" ... или так же как в переводе "Сервер NUT" - сохранить NUT и тут... это гуи для мониторинга устройств через NUT и косвенно его самого (не работает - гуи ругается и ничего не показывает...)

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "Найдено {0} ИБП на {1}"
s/ИБП/устройств/

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "Отключение от ИБП"
s/ИБП/устройства/

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "Значения"
Там по контексту как, множественное число?

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "Параметры"
Там по контексту как, множественное число?

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "Удалено '%s'"
м.б. `Удалено избранное (устройство?) '%s'` ?

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "Ошибка при сохранении Избранного (%s)"
Там по контексту как, множественное число? В переводе разных строк вперемешку "Избранное" и "Избранные" для оригинального favorites... :(

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "ИБП '%s' не найден на сервере"
`Устройство '%s' не найдено на сервере`

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "(нет защиты батарей)"
тут скорее `(нет защиты батареей)`, насколько я помню (т.е. что комп не защищен разряженной батареей, а не что сама батарея от чего-то чем-то не защищена)

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "Выполняется калибровка"
...в реальном времени?

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "слишком большая нагрузка на ИБП"
на устройство

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "Статус ИБП : "
устройства

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "В сети"
тут по контексту `Питание от сети` (возможны варианты - ИБП-то от сети, но нагрузка через фильтр в составе ИБП, прямо от сети с быстрым переключением на защиту, или всегда внутренний контур запитан от батареи которая с одной стороны подзаряжается, с другой опустошается)

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "От батарей"
тут по контексту `Питание нагрузки от батарей` (нет питания от сети, или идет калибровка и ИБП умышленно разряжается, или...)

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "Ошибка '{0}' ({1})"
Ошибка ОТ ...?

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +"Ошибка '{0}'\n"
Ошибка ОТ ...?

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "Мониторинг ИБП"
см. комментарий про как бы красиво обозвать "устройства, связанные с электропитанием"

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "Команды ИБП : "
...устройства

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "Статус ИБП"
...устройства

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "Параметры ИБП"
...устройства

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +"Введите название для данной закладки\n"
"Избранное" выше в файле - это те же "закладки"? ("favorite(s)" там и тут...)

2020-10-07 12:55 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr ""
Не уверен, что корректно удалять идентификацию (ниже), копирайты и т.п.

@aquette : Am I right that strings for GUI copyright here and (C)+GPL below, and descriptions for NUT and its GUI below, should not be dropped, but either kept as is or translated?

2020-10-08 10:48 UTC, aquette approved these changes
trusting @jimklimov  here since my Russian is still too poor

2020-10-08 11:31 UTC, melenki commented
Thank you for your comments and suggestions. Made all the changes.

2020-10-08 11:46 UTC, melenki commented on scripts/python/app/locale/ru/ru.po
> +msgstr "От батарей"
Метка у статуса в окне программы даёт понять назначение (смысл) фразы. Думаю, что слишком длинный первод "поломает" интерфейс

2020-10-08 11:48 UTC, melenki commented on scripts/python/app/locale/ru/ru.po
> +msgstr "Ошибка при сохранении Избранного (%s)"
Переделал favorites в переводе как "закладка" в зависимости от контекста в единственном или множественном числе

2020-10-08 13:17 UTC, jimklimov requested changes
Big thanks for the update! A couple more typos found in the new commits...

2020-10-08 13:17 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "Устройство '%s' не найден на сервере"
Устройство '%s' не найден_о_ на сервере

2020-10-08 13:17 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +"Укажаите закладку, которую Вы\n"
Ук_аж_ите

2020-10-08 13:19 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "От батарей"
Ok

2020-10-08 13:30 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "Загрузка ИБП :"
Тут я споткнулся... не будет ли "нагрузка" правильнее? С другой стороны, у корабля или грузовика полная или нет "загрузка" (как доля от его ёмкости) и тут это может быть ближе по контексту.

2020-10-08 13:31 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr ""
Thanks for fixing these in particular!

2020-10-08 20:15 UTC, melenki commented on scripts/python/app/locale/ru/ru.po
> +msgstr "Загрузка ИБП :"
Заглянул в учебник по электротехнике - по тексту везде используется термин "нагрузка". Исправил.

2020-10-09 09:35 UTC, jimklimov commented on scripts/python/app/locale/ru/ru.po
> +msgstr "Загрузка ИБП :"
Спасибо за расследование :)

2020-10-09 09:35 UTC, merged